### ISSUE TITLE
Declare named queues

### ISSUE THREAD

**Issue by aerosol** [muxspace/bunny_farm#3]
Hi,

``` erlang
BusHandle = bunny_farm:open(<<"exchange">>, <<"routing_key.#">>, [{queue,Q}])
```

The above function call (mentioned in README) won't work since `bunny_farm:open` has arity 2. Reading the source, it is unclear to me how to declare named queues using `bunny_farm` interface.

Could you please provide feedback on this?

**Comment by muxspace** [comment]
Hi, to use a named queue, do the following:
  Handle = bunny_farm:open(<<"">>),
  bunny_farm:publish(Message, QueueName, Handle),

I'll update the README.

**Comment by muxspace** [comment]
I updated the README and added a few more examples. Let me know if this clarifies it for you. Regards, Brian

**Comment by aerosol** [comment]
Well, as much as I love the idea behind `gen_qserver`, this isn't really intuitive at all.

Opening `<<"">>` suggests an unnamed queue, rather than named one, not to mention you don't necessarily need to publish to that queue -- imagine just plain declarative setup for that matter.

**Comment by aerosol** [comment]
I'll try to work on this. Thanks for your feedback.

**Comment by muxspace** [comment]
Hi, I'm a little confused about your penultimate comment. Which part of the gen_qserver do you find to be not intuitive? The connection specs in the gen_qserver are for consumption. These connection specs are consistent with publishing to a specific routing key. It's slightly different when publishing to an explicit queue since there is no routing key to pass to open(). The <<"">> notation is the syntax that RabbitMQ uses for the default exchange, which all queues are bound to via their queue name. [1]

[1] http://www.rabbitmq.com/erlang-client-user-guide.html

**Comment by aerosol** [comment]
Hi, I should have known better, I didn't read the user guide carefully enough. You're right; sorry for confusing you.

**Comment by muxspace** [comment]
No worries. I take non-intuitive APIs seriously, so wanted to fully understand what you were highlighting.
